"""change

Revision ID: 02b5cbc4cf67
Revises: 6cf43eae651b
Create Date: 2023-11-12 16:00:59.808264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b5cbc4cf67'
down_revision = '6cf43eae651b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=True),
    sa.Column('token_quiz', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('theme_color', sa.Text(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('request_username', sa.Boolean(), nullable=True),
    sa.Column('company_badge', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_token')
    # ### end Alembic commands ###
