"""description of the change

Revision ID: 1d5f6a7c4793
Revises: a195c601cd3b
Create Date: 2023-11-14 19:54:47.960761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5f6a7c4793'
down_revision = 'a195c601cd3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request', sa.Text(), nullable=True))
        batch_op.drop_column('request_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_username', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('request')

    # ### end Alembic commands ###
