"""description of the change

Revision ID: 2e57ce10b14d
Revises: e29ad9dcd9ee
Create Date: 2023-11-01 10:11:09.128376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e57ce10b14d'
down_revision = 'e29ad9dcd9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing_result', schema=None) as batch_op:
        batch_op.drop_column('ai_status')
        batch_op.drop_column('ai')

    # ### end Alembic commands ###
