"""description of the change

Revision ID: 4c557abaf6cc
Revises: 1d5f6a7c4793
Create Date: 2023-11-15 10:46:58.414919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c557abaf6cc'
down_revision = '1d5f6a7c4793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
