"""description of the change

Revision ID: 6cf43eae651b
Revises: 2e57ce10b14d
Create Date: 2023-11-01 12:32:02.289506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf43eae651b'
down_revision = '2e57ce10b14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing_result', schema=None) as batch_op:
        batch_op.drop_column('questions')

    # ### end Alembic commands ###
