"""description of the change

Revision ID: 770644de213f
Revises: 615c0ba3d153
Create Date: 2023-10-15 17:31:45.828400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770644de213f'
down_revision = '615c0ba3d153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing_result', schema=None) as batch_op:
        batch_op.alter_column('only',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing_result', schema=None) as batch_op:
        batch_op.alter_column('only',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
