"""description of the change

Revision ID: 79b85c434622
Revises: 5a76264685dc
Create Date: 2023-10-13 11:07:39.152742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b85c434622'
down_revision = '5a76264685dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpt_pricer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=True),
    sa.Column('price_count', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gpt_pricer')
    # ### end Alembic commands ###
