"""description of the change

Revision ID: 9a4c8007e64b
Revises: 2af781fcacb2
Create Date: 2023-10-10 17:19:18.386517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4c8007e64b'
down_revision = '2af781fcacb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anonimus_feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('anonimus_feedback')

    # ### end Alembic commands ###
