"""change

Revision ID: a195c601cd3b
Revises: 76b7c1046f10
Create Date: 2023-11-12 18:57:58.813329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a195c601cd3b'
down_revision = '76b7c1046f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
