"""description of the change

Revision ID: e29ad9dcd9ee
Revises: f6b472b66f78
Create Date: 2023-10-31 20:13:37.215887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29ad9dcd9ee'
down_revision = 'f6b472b66f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('members_multiple', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing_result', schema=None) as batch_op:
        batch_op.drop_column('members_multiple')

    # ### end Alembic commands ###
