"""description of the change

Revision ID: f6b472b66f78
Revises: 770644de213f
Create Date: 2023-10-30 23:48:26.139551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b472b66f78'
down_revision = '770644de213f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testing_result', schema=None) as batch_op:
        batch_op.drop_column('count')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
